### PR TITLE
Don't paging configure on LXC guest containers

### PR DESCRIPTION
**Pull request by pedroluislopez**

### CODE REVIEW

**Comment by ypid** [comment]
> Looks like a mirror change, correct?

Looks like it. Seems to me that both conditions should do exactly the same. What was the issue with the current version so that we can look out for such issues in future reviews? Please amend your commit to include the reason for the change.

Related to: #7 
CC: @bryanbecker

**Comment by pedroluislopez** [comment]
@ypid @drybjed 

This part of original condition: `(ansible_virtualization_role == "guest" and ansible_virtualization_type == "openvz")` always is False, the value can not be "guest" and "openvz" at the same time. So `sysctl__paging_configure` value always is True.

The solution is this:

`'{{ True if not (ansible_virtualization_role == "guest" or ansible_virtualization_type == "openvz") else False }}'` (change and by or)

Or:

`'{{ True if (ansible_virtualization_role != "guest" and ansible_virtualization_type != "openvz") else False }}'`

**Comment by ypid** [comment]
It would have been useful if you had included a truth table to make this easier for us to decide. Here we go.

#### Before

```Jinja2
True if not (ansible_virtualization_role == "guest" and ansible_virtualization_type == "openvz") else False
```

```
                 | role: "guest"        | role: "host"
-------------    | -------------        | -------------
type: "openvz"   | Not configure paging | configure paging
type: "other"    | configure paging     | configure paging
```

(GitHub markdown broken. Posting as verbatim.)

#### Current PR

```Jinja2
True if (ansible_virtualization_role != "guest" and ansible_virtualization_type != "openvz") else False

{# Alternative proposal which should have has the same effect as the PR: #}
True if not (ansible_virtualization_role == "guest" or ansible_virtualization_type == "openvz") else False
```

```
                | role: "guest"        | role: "host"
-------------   | -------------        | -------------
type: "openvz"  | Not configure paging | Not configure paging
type: "other"   | Not configure paging | configure paging
```

#### What is this fix about

> value can not be "guest" and "openvz" at the same time

`ansible_virtualization_role` and `ansible_virtualization_type` are two different variables. I see no reason why they could not be "guest" and "openvz" for a openvz container. I just confirmed this for LXC which gives "guest" + "lxc". After all, the current condition has a purpose.

Your updated condition is a bit too board which I don’t think is intended. Why would we refrain from configuring paging on systems which might host OpenVZ containers? Please be specific. A commit message with "Fix virtualization condition" is not very nice. What did you try? What did not work which caused you to open this PR? Also, your reasoning needs to be preserved in the Git commit message itself. We don‘t want to rely on Github for this when we have decentralized systems like git.

**Comment by pedroluislopez** [comment]
@drybjed @ypid Ok, sorry, now I understand the condition.

My problem is with LXC guest containers. I have uploaded other change in order to not configure paging on LXC guest containers.

**Comment by ganto** [comment]
Nice 👍  I guess this would also address #8

**Comment by pedroluislopez** [comment]
@ypid Done!

**Pull request merged**
